name: Run tests

on:

  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Proceed tests
        run: mvn test

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v3
      - name: Build app
        run: mvn clean package
