name: CI

on:

  push:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Proceed tests
        run: mvn test
